### ISSUE TITLE
To test

### ISSUE THREAD

**Issue by madcato** [madcato/LongPomo#32]
- [ ] Time settings persists between sessions
- [ ] Sarts/stops timer
- [ ] Notification shows in Mac at finish
- [ ] Notification shows in iOS, with sound,  at finish 
- [ ] Notification haptic in Apple Watch,  at finish
- [ ] Starting the timer in Apple Watch, starts all other devices
- [ ] Starting the timer in Mac, starts all other devices
- [ ] Starting the timer in iOS, starts all other devices
- [ ] Starting the timer in Apple TV, starts all other devices
